version: 2
mkdocs:
  configuration: mkdocs.yml
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      # Install dependencies
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --only doc
