site_name: Easy Bigquery

repo_url: https://github.com/AndreAmorim05/easy-bigquery/tree/develop
repo_name: AndreAmorim05/easy-bigquery
edit_uri: tree/main/docs

theme:
  name: material # readthedocs
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - assets/stylesheets/extra.css

watch:
  - easy_bigquery

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [easy_bigquery]

extra:
  commands:
    install: pip install easy_bigquery
